CREATE DATABASE USER COLLATE "UTF8_GENERAL_CI"

CREATE TABLE USERS (
    ID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50)
);
/*  */
CREATE PROCEDURE `spInsertUser`(IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER


BEGIN 
INSERT INTO USER ( NAME ) VALUES (_NAME); 
END;

CALL spInsertUser('JUliancho');
/*  */
CREATE PROCEDURE `spFindAllUser`() NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
/*  */
BEGIN 
SELECT ID, NAME FROM USER; 
END;

CALL spFindAllUser()

/*  */
CREATE PROCEDURE `spFindUser`(IN `ID` INT(5)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
/*  */
BEGIN 
SELECT ID, NAME FROM USERS WHERE ID = _ID; 
END;

CALL spFindUser(1);

/*  */
CREATE PROCEDURE `spUpdateUser`(IN `_ID` INT(5), IN `_NAME` VARCHAR(50)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
/*  */
begin 
UPDATE users SET NAME = _NAME WHERE ID = _ID; 
end;

CALL `spUpdateUser`(2, `JUANES`);

/*  */
CREATE PROCEDURE `spDeleteUser`(IN `ID` INT(5)) NOT DETERMINISTIC CONTAINS SQL SQL SECURITY DEFINER 
/*  */
BEGIN 
ELETE FROM USERS WHERE ID= _ID; 
END;


 CALL `spDeleteUser`(2);
